### ISSUE TITLE
Add command tree with typical ignores

### ISSUE THREAD

**Issue by basicthinker** [covespace/devchat-vscode#135]
I heavily need `tree`. For a python project, `tree -I '__pycache__|\.pytest_cache'` should work in most cases. We can include typical ignores for different programming languages and provide a `tree` command.

**Comment by basicthinker** [comment]
Is there a way to extend this list by users? Maybe before the extensible workflow engine, this can be a low-hanging fruit? @yangbobo2021

**Comment by basicthinker** [comment]
For a next.js project: `tree -I 'node_modules|\.next'`

**Comment by yangbobo2021** [comment]
Yes, user can define his tree command now.
