### ISSUE TITLE
Error message mixed in reply

### ISSUE THREAD

**Issue by basicthinker** [covespace/devchat-vscode#147]
When a reply is interrupted by a connection issue, for example, the error message may appear in a code block. Can you add it to the scope outside the markdown-rendered area?

<img width="400" alt="image" src="https://github.com/covespace/devchat-vscode/assets/592493/8a31dcbf-b838-4987-a1e5-bbc9d2aa73c7">

**Comment by runjinz** [comment]
Fixed, the result is as follows.
![image](https://github.com/covespace/devchat-vscode/assets/12482039/ff44bf89-7d7e-450a-887e-ce2e9d3d6d11)
