### ISSUE TITLE
[Feature] Adding preset prompts for repeated use 

### ISSUE THREAD

**Issue by narrowizard** [covespace/devchat-vscode#55]
## Background
As a user of devchat, I often find myself needing to write prompt to tell DevChat to write commit messages for my code changes using semantic commit message. always repeating job. I believe this process could be streamlined if there were preset prompts available that I could select and automatically insert into my messages.

## Request
I would like to request the addition of preset prompts to devchat, or the ability for users to create and save their own custom prompts. This enhancement would make it easier and faster to complete repeated tasks, such as writing commit messages.

**Comment by yangbobo2021** [comment]
In your work dir, there is a .chat/workflows directory, you can create your custom command in there. Fox example, there 
 are code and commit_message commands.

**Comment by basicthinker** [comment]
@narrowizard a user test: did you find that typing `/` can bring in command shortcuts like `/commit_message`?

**Comment by narrowizard** [comment]
Got it, and I can now easily write a commit message in luxun's style from DevChat.  
> did you find that typing / can bring in command shortcuts like /commit_message?  

Didn't know until now, maybe add a tips on placeholder is better.

**Comment by yangbobo2021** [comment]
Add new custom command has a handle error, it will fix in 0.0.31. I have fix it.
