### ISSUE TITLE
Why only "Click to revert change"?

### ISSUE THREAD

**Issue by basicthinker** [covespace/devchat-vscode#61]
Now I only see "Click to revert change" with semantic diff. Why? It will be perfect to have an operation in the opposite direction, like "Click to apply change". Is it supported by semantic diff? It should be. If so, I think it already solves the problem. We don't need to move code back and forth as @yangbobo2021 suggested. Users can easily understand the generated code is not a full file. They won't pay much attention to the omitted code. Instead, they only need to and will naturally focus on the added or modified code blocks. Semantic diff supports operations on those individual code blocks. That's good enough, at least for now.
<img width="721" alt="image" src="https://github.com/covespace/devchat-vscode/assets/592493/34be5219-2b65-425b-9103-ec069d00a489">

**Comment by yangbobo2021** [comment]
We have not yet done any work on the diff view, and the existing menus or buttons are provided by vscode default or other plugins. We will have more work in the diff view in the future.
