### ISSUE TITLE
[Feature] Add env support in instruct.txt

### ISSUE THREAD

**Issue by narrowizard** [covespace/devchat-vscode#74]
For example, my prompt is as following
```
please write a semantic commit message for the diff, releated issue id is ${branchName}
```

**Comment by basicthinker** [comment]
Better to see the value someway in case of typos. At least, `$` should trigger a list of env to choose from or press tab to complete one.

**Comment by narrowizard** [comment]
In my use case, I have delegated the task of writing commit messages to DevChat. The goal is to provide a complete prompt with just the command /commit_message. In general, we use the issue_id as the branch name. If this information can be included in the `instruct.txt`, there's no need to input "related Jira issue is $branchName" every time.

Additionally, adding a shortcut to reference environment variables during input would be a useful feature.

**Comment by yangbobo2021** [comment]
This feature has supported in version 0.1.7. for example: ${branchName} will replaced by env var branchName.
